# Enable or disable the ServiceEntry resources.
enabled: true


# Shared ServiceEntries deployed on every tenant cluster.
commonServiceEntries:
  - name: github-api
    namespace: istio-system
    hosts:
      - api.github.com
    ports:
      - number: 443
        name: https
        protocol: HTTPS
    location: MESH_EXTERNAL
    resolution: DNS

# Tenant-specific ServiceEntries. Override in values-${tenantName}.yaml.
serviceEntries: []
