apiVersion: v2
name: podinfo
description: Wrapper chart for podinfo with value overrides
type: application
version: 1.0.2
appVersion: "6.14.0"

dependencies:
  - name: podinfo
    version: 6.14.0
    repository: oci://ghcr.io/stefanprodan/charts
    condition: enabled
