apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: istio-service-entry
  namespace: istio-system
spec:
  interval: 1m
  dependsOn:
    - name: istio-control-plane
      namespace: istio-system
  chart:
    spec:
      chart: ${helmChartDirectory}/istio-service-entry
      # repackage and redeploy on every new Git commit (default ChartVersion only triggers on Chart.yaml version bumps)
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-sync
        namespace: flux-system
      interval: 1m
      # last values file takes precedence
      valuesFiles:
        - ${helmChartDirectory}/istio-service-entry/values-${tenantName}.yaml
      # ignore missing values files
      ignoreMissingValuesFiles: true
