apiVersion: v1
kind: Namespace
metadata:
  name: istio-cni
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
# Namespace for the podinfo application
apiVersion: v1
kind: Namespace
metadata:
  name: podinfo
  labels:
    istio-injection: enabled
