apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: ./helm-charts/podinfo
      # repackage and redeploy on every new Git commit (default ChartVersion only triggers on Chart.yaml version bumps)
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: flux-sync
        namespace: flux-system
      interval: 1m
      # last values file takes precedence
      valuesFiles:
        - ./helm-charts/podinfo/values-${tenantName}.yaml
      # ignore missing values files
      ignoreMissingValuesFiles: true
